### ISSUE TITLE
Встраивание на страницу

### ISSUE THREAD

**Issue by radist** [Pathologic/SimpleTube#11]
Добрый день.

Как встроить видео на страницу? Вот так оно почему то, скачивается:
```
 <iframe width="560" height="315" src="[+st_embedUrl+]" frameborder="0" allowfullscreen></iframe>
```
Отрендереный код выглядит так:
```
<iframe width="560" height="315" src="http://www.youtube.com/v/9bZkp7q19f0" frameborder="0" allowfullscreen=""></iframe>
```
Вот такой код работает:

```
<iframe width="560" height="315" src="http://www.youtube.com/embed/9bZkp7q19f0" frameborder="0" allowfullscreen=""></iframe>
```

Разница в URL "v" или "embed"

Уточнение. Данная проблема возникает например в chromium, (или в любом другом браузере при отсутствии флеш плеера).

**Comment by Pathologic** [comment]
Это проблема youtube - он отдает такую именно ссылку через api. Учитывая, что не все видео youtube может показывать с html5-проигрывателем, я не знаю, как тут лучше поступить - можно подменять ссылку при выводе через prepare-сниппет; можно проверять через js наличие флеш и тогда подменять ссылку c помощью js. Или вообще встраивать через iframe-api: https://developers.google.com/youtube/iframe_api_reference?hl=ru

**Comment by Pathologic** [comment]
Попробовал поменять /v/ на /embed/ (тем более, что если брать код вручную с ютуба, то там embed) - ничего не сломалось, но при этом видео показывается и без флеша. Будем считать, что проблема решена.
Обновить уже добавленные ссылки можно запросом
```
UPDATE modx_st_videos SET st_embedUrl = REPLACE (st_embedUrl, '/v/','/embed/')

**Comment by radist** [comment]
Спасибо.
