### ISSUE TITLE
YouTube APIv3

### ISSUE THREAD

**Issue by AgelxNash** [Pathologic/SimpleTube#13]
Новая версия Panorama поддерживает APIv3. Но просто так не обновиться, т.к. возникает 2 проблемы:
 - Новая версия не работает с PHP 5.3. Добавить поддержку не так уж и сложно - там всего лишь используется сокращенная запись массивов.
 - Сам SimpleTube [не передает параметры в конструктор](https://github.com/Pathologic/SimpleTube/blob/master/assets/snippets/simpletube/lib/SimpleTube/simpletube.class.php#L45), а значит и ключ API никак не передать...

**Comment by Pathologic** [comment]
https://github.com/Pathologic/SimpleTube/commit/45dbcd8f55d341c987c7e96c007c5c4ef49cc2ae
