### ISSUE TITLE
Пустой таб на 1.2

### ISSUE THREAD

**Issue by sashabeep** [Pathologic/SimpleTube#15]
Добрый день, после обновления админки до 1.2 таб пустой. Несколько миллисекунд показывается заголовок, потом таб становится пустым. Видимо, сбоит какая-то JS-функция.
ManagerManager тоже из дефолтной поставки 1.2
Переустанавливал из магазина - эффект тот же

**Comment by sashabeep** [comment]
https://github.com/Pathologic/SimpleTube/pull/16/commits/ada18bdea54d2c4f830f885d02c04787e0c6c2ca

**Comment by sashabeep** [comment]
#16

**Comment by Pathologic** [comment]
Димины пулреквесты проблему решают, но не до конца. После праздников займусь переписыванием всего.
