### ISSUE TITLE
Не показываются превью

### ISSUE THREAD

**Issue by sashabeep** [Pathologic/SimpleTube#17]
После обновления до 1.2.1 и обновлении SimpleTube из стора на двух сайтах наблюдается странная ошибка - не отображаются превью в виджете. При открытии картинки по ссылке пишет что изображение с ошибками. Весь остальной функционал работает, видео добавляются, картинки автоматом загружаются, только в виджете не показываются. Что можно с ними сделать?

![2017-05-30 14 59 31](https://cloud.githubusercontent.com/assets/5689796/26582205/eedf2d24-4548-11e7-949f-a52ea16159e1.jpg)

**Comment by Pathologic** [comment]
Такое было у одного-двух человек, решить не удалось.   Если будет инструкция, как мне воспроизвести проблему у себя, то я займусь решением, а пока жалко  тратить время впустую.
