### ISSUE TITLE
Всегда запрашивать HTTPS

### ISSUE THREAD

**Issue by Aharito** [Pathologic/SimpleTube#22]
Если сайт на HTTPS, и видео из **YouTube**, то появляется такое сообщение и видео не загружается.

![image](https://user-images.githubusercontent.com/6253807/33375762-8bc73c60-d53d-11e7-91b4-42b0f3712573.png)

Так как **YouTube** уже полностью на **HTTPS**, то можно и запрашивать сразу https.

То же самое и для других - Vimeo, Vk иТ.д.

**Comment by Pathologic** [comment]
https://github.com/Pathologic/SimpleTube/pull/23
